import { SidebarProvider } from "@/components/ui/sidebar";

import { AppSidebar } from "@/components/app-sidebar";
import { GeoProvider } from "@/context/GeoProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = await headers();
  const geo = {
    country: header.get("x-vercel-ip-country") || "Unknown",
    latitude: parseFloat(header.get("x-vercel-ip-latitude") || "0"),
    longitude: parseFloat(header.get("x-vercel-ip-longitude") || "0"),
  };

  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <GeoProvider value={geo}>
          <SidebarProvider>
            <AppSidebar />
            {children}
          </SidebarProvider>
        </GeoProvider>
      </body>
    </html>
  );
}
